stages:
  - build
  - push
  - dev

before_script:
  - set -e
  - TAG="${CI_COMMIT_TAG}"
  - if [ -z "${TAG}" ]; then TAG=${CI_COMMIT_REF_SLUG}; fi
  - if [ "${TAG}" = "master" ]; then TAG=${CI_COMMIT_SHA}; fi
  - echo "TAG => " ${TAG}
  - echo "DEPLOY_NAME => " ${DEPLOY_NAME}
  - echo "CI_ENVIRONMENT_SLUG => " ${CI_ENVIRONMENT_SLUG}

build:
  stage: build
  script:
    - nix-build nix/release.nix
  tags:
    - nix

push-email-master:
  stage: push
  script:
    - nix-build nix/release.nix
    - docker login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}"
    - docker load < ./result
    - docker tag registry.sirius.online/cheops-edu/cheops-email/cheops-email:latest registry.sirius.online/cheops-edu/cheops-email/cheops-email:${CI_COMMIT_SHA}
    - docker push registry.sirius.online/cheops-edu/cheops-email/cheops-email:${CI_COMMIT_SHA}
  tags:
    - nix
  except:
    - schedules
  only:
    - master

.base-email-deploy: &base-email-deploy
  except:
    - schedules
  when: manual
  script:
   - set -x
   - kubectl get ns "email-${CI_ENVIRONMENT_SLUG}" || kubectl create ns "email-${CI_ENVIRONMENT_SLUG}"
   - export MAILER_PASSWORD="${DEPLOY_NAME}_mailer_password"
   - export MAILER_USER="${DEPLOY_NAME}_mailer_user"
   - export DB_URI="${DEPLOY_NAME}_db_uri"
   - helm upgrade
      --install "email-${CI_ENVIRONMENT_SLUG}" deploy/helm/charts/email/
      -f "deploy/helm/charts/email/charts/${DEPLOY_NAME}/default.yaml"
      -f "deploy/helm/charts/email/charts/${DEPLOY_NAME}/${CI_ENVIRONMENT_SLUG}.yaml"
      --set global.env="${CI_ENVIRONMENT_SLUG}"
      --set global.tag="${TAG}"
      --set global.url="${CI_ENVIRONMENT_URL}"
      --set email.smtp.password="${!MAILER_PASSWORD}"
      --set email.smtp.userEmail="${!MAILER_USER}"
      --set email.db.main.uri="${!DB_URI}"
      --set deploy_name="${DEPLOY_NAME}"
      --namespace="email-${CI_ENVIRONMENT_SLUG}"
      --wait
  only:
    - tags

.base-email-sirius-deploy: &base-email-sirius-deploy
  <<:  *base-email-deploy
  variables:
    CLUSTER_NAME: "SIRIUS"
    DEPLOY_NAME: "sirius"
  tags:
    - kube-ci

.base-email-cpm-deploy: &base-email-cpm-deploy
  <<: *base-email-deploy
  variables:
     CLUSTER_NAME: "CPM"
     DEPLOY_NAME: "cpm"
  tags:
     - kube-cpm

sirius email dev:
  <<: *base-email-sirius-deploy
  stage: dev
  variables:
     STAGE_NAME: "DEV"
     DEPLOY_NAME: "sirius"
  environment:
    name: dev
  only:
   - master

cpm email dev:
  <<: *base-email-cpm-deploy
  stage: dev
  variables:
     STAGE_NAME: "DEV"
     DEPLOY_NAME: "cpm"
  environment:
    name: dev
  only:
    - master
